name: "build-test"
on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Building & testing @bitwarden/sm-action for - ${{ matrix.settings.os }}
    runs-on: ${{ matrix.settings.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: macos-12
            target: x86_64-apple-darwin
            build: |
              npm run dist
              npm run test

          - os: windows-2022
            target: x86_64-pc-windows-msvc
            build: |
              npm run dist
              npm run test

          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            build: |
              npm run dist
              npm run test
    steps:
      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 20
          cache-dependency-path: "**/package-lock.json"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: ${{ matrix.settings.build }}
