---
name: Lint

on:
  push:
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:
    inputs: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          node-version: "18"

      - name: Run linter
        run: |
          npm ci
          npm run lint
