name: "qa-run"
on:
  workflow_dispatch:
    inputs:
      apiUrl:
        description: "API URL to use"
        required: true
        type: string
      identityUrl:
        description: "Identity URL to use"
        required: true
        type: string
      secretId:
        description: "Secret GUID to use"
        required: true
        type: string

jobs:
  run:
    name: Running QA test on ${{ matrix.settings.os }}
    runs-on: ${{ matrix.settings.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: macos-13
          - os: macos-14
          - os: windows-2022
          - os: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run Action
        uses: ./
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          api_url: ${{ inputs.apiUrl }}
          identity_url: ${{ inputs.identityUrl }}
          secrets: |
            ${{inputs.secretId}} > TEST_EXAMPLE
      - name: Show secrets
        shell: bash
        run: echo $TEST_EXAMPLE is secrets value
