name: "qa-run"
on:
  workflow_dispatch:
    inputs:
      apiUrl:
        description: "API URL to use"
        required: true
        type: string
      identityUrl:
        description: "Identity URL to use"
        required: true
        type: string
      secretId:
        description: "Secret GUID to use"
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Run Action
        uses: ./
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          api_url: ${{ inputs.apiUrl }}
          identity_url: ${{ inputs.identityUrl }}
          secrets: |
            ${{inputs.secretId}} > TEST_EXAMPLE
      - name: Show secrets
        run: echo $TEST_EXAMPLE is secrets value
